package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"
)

func main() {
	file, err := os.OpenFile("./hankaku.txt", os.O_RDONLY, 0666)
	if err != nil {
		panic(err)
	}
	defer file.Close()
	br := bufio.NewReader(file)

	res := make([]string, 0)

	isStarted := false
	for {
		line, err := br.ReadSlice('\n')
		if err != nil {
			if err == io.EOF {
				break
			}
			panic(err)
		}
		if !isStarted && len(line) > 4 && string(line[:4]) == "char" {
			isStarted = true
		}
		if isStarted && len(line) > 4 && string(line[:4]) != "char" {
			res = append(res, string(line))
		}
	}

	mid := make([]string, 0, len(res))
	for _, l := range res {
		mid = append(mid, fmt.Sprintf("\"%s\"", l[:8]))
	}
	w := strings.Join(mid, ",\n")
	ccode := "// This file is auto generated by hankafu/main.go, please don't modify directly\n\n"
	ccode += "char hankaku[4096][8] =  {\n" + w + "};\n"

	o, err := os.Create("hankaku.c")
	if err != nil {
		panic(err)
	}
	defer o.Close()
	_, _ = o.WriteString(ccode)
}
